site_name: Edge AI x86 Computer for Robots
nav:
  - Home: index.md
  - Getting Started Guide: quick-start.md
  - Software Guide: 
    - Converting models: software-guide/converting.md
  - DocsHowto: docs-howto.md

theme:
  name: readthedocs
  palette:
    primary: brown

markdown_extensions:
  - attr_list