site_name: Fast Sense X Robotics AI Platform
nav:
  - Home: index.md
  - Getting Started: quick-start.md
  - Software Guide:
    - Table demo: software-guide/table-demo.md
    - NNIO: software-guide/nnio.md
    - Converting models: software-guide/converting.md
  - Hardware Guide:
    - UART how-to: hardware-guide/com-port-howto.md
    - Interface tests: hardware-guide/interface-tests.md
    - Telemetry: hardware-guide/telemetry.md
    - Console redirection: hardware-guide/console-redir.md

theme:
  name: readthedocs
  palette:
    primary: brown

markdown_extensions:
  - attr_list
  - admonition

extra_css:
    - 'stylesheets/extra.css'